[build]
  command = "npm run build"
  publish = "dist"

[ceview]
  command = "npm run build-ontext.deploy-prpreview"

[template.environment]
  STATUSKIT_PAGE_TITLE = "Spearhead Cloud Status"
  STATUSKIT_COMPANY_LOGO = "http://spearhead.systems/static/img/sphstop.png"
  STATUSKIT_SUPPORT_CONTACT_LINK = "url to your support page"
  STATUSKIT_RESOURCES_LINK = "https://docs.spearhead.cloud"
